// Auto-generated icon mapping for StarCraft 2 units
export interface UnitIconMapping extends Record<string, string> {}

export const UNIT_ICON_MAPPING: UnitIconMapping = {
  // Terran units (using sc2reader names)
  CommandCenter: "/icons/sc2/terran/command_center.svg",
  OrbitalCommand: "/icons/sc2/terran/orbital_command.svg",
  PlanetaryFortress: "/icons/sc2/terran/planetary_fortress.svg",
  SupplyDepot: "/icons/sc2/terran/supply_depot.svg",
  Barracks: "/icons/sc2/terran/barracks.svg",
  Factory: "/icons/sc2/terran/factory.svg",
  Starport: "/icons/sc2/terran/starport.svg",
  EngineeringBay: "/icons/sc2/terran/engineering_bay.svg",
  Armory: "/icons/sc2/terran/armory.svg",
  Refinery: "/icons/sc2/terran/refinery.svg",
  Bunker: "/icons/sc2/terran/bunker.svg",
  MissileTurret: "/icons/sc2/terran/bunker.svg", // Reuse bunker for now
  SensorTower: "/icons/sc2/terran/engineering_bay.svg", // Reuse engineering bay

  // Addons (sc2reader specific names)
  BarracksTechLab: "/icons/sc2/terran/tech_lab.svg",
  FactoryTechLab: "/icons/sc2/terran/tech_lab.svg",
  StarportTechLab: "/icons/sc2/terran/tech_lab.svg",
  BarracksReactor: "/icons/sc2/terran/reactor.svg",
  FactoryReactor: "/icons/sc2/terran/reactor.svg",
  StarportReactor: "/icons/sc2/terran/reactor.svg",
  BehemothReactor: "/icons/sc2/terran/reactor.svg",

  TechLab: "/icons/sc2/terran/tech_lab.svg",
  Reactor: "/icons/sc2/terran/reactor.svg",
  Academy: "/icons/sc2/terran/academy.svg",
  FusionCore: "/icons/sc2/terran/fusion_core.svg",
  GhostAcademy: "/icons/sc2/terran/ghost_academy.svg",

  // Units
  SCV: "/icons/sc2/terran/scv.svg",
  Marine: "/icons/sc2/terran/marine.svg",
  Marauder: "/icons/sc2/terran/marauder.svg",
  Reaper: "/icons/sc2/terran/reaper.svg",
  Ghost: "/icons/sc2/terran/ghost.svg",
  Hellion: "/icons/sc2/terran/hellion.svg",
  Hellbat: "/icons/sc2/terran/hellbat.svg",
  WidowMine: "/icons/sc2/terran/widow_mine.svg",
  Cyclone: "/icons/sc2/terran/cyclone.svg",
  SiegeTank: "/icons/sc2/terran/siege_tank.svg",
  Thor: "/icons/sc2/terran/thor.svg",
  Medivac: "/icons/sc2/terran/medivac.svg",
  Liberator: "/icons/sc2/terran/liberator.svg",
  Viking: "/icons/sc2/terran/viking.svg",
  Raven: "/icons/sc2/terran/raven.svg",
  Banshee: "/icons/sc2/terran/banshee.svg",
  Battlecruiser: "/icons/sc2/terran/battlecruiser.svg",

  // Terran Upgrades/Research (using generic tech icon)
  Stimpack: "/icons/sc2/terran/academy.svg",
  CombatShield: "/icons/sc2/terran/academy.svg",
  ConcussiveShells: "/icons/sc2/terran/academy.svg",
  HiSecAutoTracking: "/icons/sc2/terran/engineering_bay.svg",
  CloakingField: "/icons/sc2/terran/ghost_academy.svg",
  TerranVehicleAndShipArmorsLevel1: "/icons/sc2/terran/armory.svg",
  TerranVehicleAndShipArmorsLevel2: "/icons/sc2/terran/armory.svg",
  TerranVehicleAndShipArmorsLevel3: "/icons/sc2/terran/armory.svg",

  // Protoss units
  Nexus: "/icons/sc2/protoss/nexus.svg",
  Pylon: "/icons/sc2/protoss/pylon.svg",
  Gateway: "/icons/sc2/protoss/gateway.svg",
  Warpgate: "/icons/sc2/protoss/warpgate.svg",
  Assimilator: "/icons/sc2/protoss/assimilator.svg",
  Forge: "/icons/sc2/protoss/forge.svg",
  PhotonCannon: "/icons/sc2/protoss/photon_cannon.svg",
  CyberneticsCore: "/icons/sc2/protoss/cybernetics_core.svg",
  Stargate: "/icons/sc2/protoss/stargate.svg",
  Robotics: "/icons/sc2/protoss/robotics_facility.svg",
  RoboticsBay: "/icons/sc2/protoss/robotics_bay.svg",
  FleetBeacon: "/icons/sc2/protoss/fleet_beacon.svg",
  TemplarArchives: "/icons/sc2/protoss/templar_archives.svg",
  DarkShrine: "/icons/sc2/protoss/dark_shrine.svg",
  TwilightCouncil: "/icons/sc2/protoss/twilight_council.svg",
  ShieldBattery: "/icons/sc2/protoss/shield_battery.svg",
  Probe: "/icons/sc2/protoss/probe.svg",
  Zealot: "/icons/sc2/protoss/zealot.svg",
  Stalker: "/icons/sc2/protoss/stalker.svg",
  Sentry: "/icons/sc2/protoss/sentry.svg",
  Adept: "/icons/sc2/protoss/adept.svg",
  HighTemplar: "/icons/sc2/protoss/high_templar.svg",
  DarkTemplar: "/icons/sc2/protoss/dark_templar.svg",
  Archon: "/icons/sc2/protoss/archon.svg",
  Observer: "/icons/sc2/protoss/observer.svg",
  Immortal: "/icons/sc2/protoss/immortal.svg",
  WarpPrism: "/icons/sc2/protoss/warp_prism.svg",
  Colossus: "/icons/sc2/protoss/colossus.svg",
  Disruptor: "/icons/sc2/protoss/disruptor.svg",
  Phoenix: "/icons/sc2/protoss/phoenix.svg",
  Oracle: "/icons/sc2/protoss/oracle.svg",
  VoidRay: "/icons/sc2/protoss/void_ray.svg",
  Tempest: "/icons/sc2/protoss/tempest.svg",
  Carrier: "/icons/sc2/protoss/carrier.svg",
  Mothership: "/icons/sc2/protoss/mothership.svg",

  // Zerg units (using sc2reader names)
  Hatchery: "/icons/sc2/zerg/hatchery.svg",
  Lair: "/icons/sc2/zerg/lair.svg",
  Hive: "/icons/sc2/zerg/hive.svg",
  Extractor: "/icons/sc2/zerg/extractor.svg",
  SpawningPool: "/icons/sc2/zerg/spawning_pool.svg",
  EvolutionChamber: "/icons/sc2/zerg/evolution_chamber.svg",
  RoachWarren: "/icons/sc2/zerg/roach_warren.svg",
  BanelingNest: "/icons/sc2/zerg/baneling_nest.svg",
  CreepTumor: "/icons/sc2/zerg/creep_tumor.svg",
  SpineCrawler: "/icons/sc2/zerg/spine_crawler.svg",
  SporeCrawler: "/icons/sc2/zerg/spore_crawler.svg",
  HydraliskDen: "/icons/sc2/zerg/hydralisk_den.svg",
  LurkerDen: "/icons/sc2/zerg/lurker_den.svg",
  LurkerDenMP: "/icons/sc2/zerg/lurker_den.svg", // sc2reader specific name
  Infestation: "/icons/sc2/zerg/infestation_pit.svg",
  InfestationPit: "/icons/sc2/zerg/infestation_pit.svg", // sc2reader specific name
  Spire: "/icons/sc2/zerg/spire.svg",
  GreaterSpire: "/icons/sc2/zerg/greater_spire.svg",
  NydusNetwork: "/icons/sc2/zerg/nydus_network.svg",
  NydusCanal: "/icons/sc2/zerg/nydus_network.svg", // sc2reader specific name
  UltraliskCavern: "/icons/sc2/zerg/ultralisk_cavern.svg",

  // Zerg units
  Larva: "/icons/sc2/zerg/larva.svg",
  Drone: "/icons/sc2/zerg/drone.svg",
  Zergling: "/icons/sc2/zerg/zergling.svg",
  Baneling: "/icons/sc2/zerg/baneling.svg",
  Queen: "/icons/sc2/zerg/queen.svg",
  Roach: "/icons/sc2/zerg/roach.svg",
  Ravager: "/icons/sc2/zerg/ravager.svg",
  Hydralisk: "/icons/sc2/zerg/hydralisk.svg",
  Lurker: "/icons/sc2/zerg/lurker.svg",
  Infestor: "/icons/sc2/zerg/infestor.svg",
  SwarmHost: "/icons/sc2/zerg/swarm_host.svg",
  Ultralisk: "/icons/sc2/zerg/ultralisk.svg",
  Overseer: "/icons/sc2/zerg/overseer.svg",
  Overlord: "/icons/sc2/zerg/overlord.svg",
  Mutalisk: "/icons/sc2/zerg/mutalisk.svg",
  Corruptor: "/icons/sc2/zerg/corruptor.svg",
  BroodLord: "/icons/sc2/zerg/brood_lord.svg",
  Viper: "/icons/sc2/zerg/viper.svg",

  // Zerg Upgrades/Research (using generic building icons)
  Burrow: "/icons/sc2/zerg/hatchery.svg",
  overlordspeed: "/icons/sc2/zerg/hatchery.svg", // sc2reader specific name
  EvolveGroovedSpines: "/icons/sc2/zerg/hydralisk_den.svg",
  EvolveMuscularAugments: "/icons/sc2/zerg/hydralisk_den.svg",
  ZergGroundArmorsLevel1: "/icons/sc2/zerg/evolution_chamber.svg",
  ZergGroundArmorsLevel2: "/icons/sc2/zerg/evolution_chamber.svg",
  ZergGroundArmorsLevel3: "/icons/sc2/zerg/evolution_chamber.svg",
  ZergMeleeWeaponsLevel1: "/icons/sc2/zerg/evolution_chamber.svg",
  ZergMeleeWeaponsLevel2: "/icons/sc2/zerg/evolution_chamber.svg",
  ZergMeleeWeaponsLevel3: "/icons/sc2/zerg/evolution_chamber.svg",
  ZergMissileWeaponsLevel1: "/icons/sc2/zerg/evolution_chamber.svg",
  ZergMissileWeaponsLevel2: "/icons/sc2/zerg/evolution_chamber.svg",
  ZergMissileWeaponsLevel3: "/icons/sc2/zerg/evolution_chamber.svg",

  // Common actions
  Canceling: "/icons/sc2/neutral/unknown.svg", // Generic cancel action
};

export const getRaceFromUnit = (unitName: string): string => {
  if (
    [
      "CommandCenter",
      "OrbitalCommand",
      "PlanetaryFortress",
      "SupplyDepot",
      "Barracks",
      "Factory",
      "Starport",
      "EngineeringBay",
      "Armory",
      "Refinery",
      "Bunker",
      "TechLab",
      "Reactor",
      "Academy",
      "FusionCore",
      "GhostAcademy",
      "SCV",
      "Marine",
      "Marauder",
      "Reaper",
      "Ghost",
      "Hellion",
      "Hellbat",
      "WidowMine",
      "Cyclone",
      "SiegeTank",
      "Thor",
      "Medivac",
      "Liberator",
      "Viking",
      "Raven",
      "Banshee",
      "Battlecruiser",
    ].includes(unitName)
  )
    return "terran";
  if (
    [
      "Nexus",
      "Pylon",
      "Gateway",
      "Warpgate",
      "Assimilator",
      "Forge",
      "PhotonCannon",
      "CyberneticsCore",
      "Stargate",
      "Robotics",
      "RoboticsBay",
      "FleetBeacon",
      "TemplarArchives",
      "DarkShrine",
      "TwilightCouncil",
      "ShieldBattery",
      "Probe",
      "Zealot",
      "Stalker",
      "Sentry",
      "Adept",
      "HighTemplar",
      "DarkTemplar",
      "Archon",
      "Observer",
      "Immortal",
      "WarpPrism",
      "Colossus",
      "Disruptor",
      "Phoenix",
      "Oracle",
      "VoidRay",
      "Tempest",
      "Carrier",
      "Mothership",
    ].includes(unitName)
  )
    return "protoss";
  if (
    [
      "Hatchery",
      "Lair",
      "Hive",
      "Extractor",
      "SpawningPool",
      "EvolutionChamber",
      "RoachWarren",
      "BanelingNest",
      "CreepTumor",
      "SpineCrawler",
      "SporeCrawler",
      "HydraliskDen",
      "LurkerDen",
      "Infestation",
      "Spire",
      "GreaterSpire",
      "NydusNetwork",
      "UltraliskCavern",
      "Larva",
      "Drone",
      "Zergling",
      "Baneling",
      "Queen",
      "Roach",
      "Ravager",
      "Hydralisk",
      "Lurker",
      "Infestor",
      "SwarmHost",
      "Ultralisk",
      "Overseer",
      "Overlord",
      "Mutalisk",
      "Corruptor",
      "BroodLord",
      "Viper",
    ].includes(unitName)
  )
    return "zerg";
  return "neutral";
};

export const getUnitIcon = (unitName: string): string => {
  return UNIT_ICON_MAPPING[unitName] ?? "/icons/sc2/neutral/unknown.svg";
};
